default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
  database: codenyan_development
  socket: /tmp/mysql.sock

test:
  <<: *default
  adapter: mysql2
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
  database: codenyan_test
  socket: /tmp/mysql.sock

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>